### ISSUE TITLE
Upgrade Decidim to version 0.14.3

### ISSUE THREAD

**Issue by xredo** [vilanovailageltru/decidim-vilanova#42]
The current installed version is 0.2.0.

## Tasks

- [x] Upgrade Ruby version
- [x] Upgrade Decidim dependencies
- [x] Adapt the Vilanova AuthorizationHandler code to the new Authorization format supported by Decidim
- [x] Validate reported errors are already solved (#22, #23)
